### ISSUE TITLE
Reset Salt

### ISSUE THREAD

**Issue by mistakevin** [mistakevin/aca-campus#4]

**Comment by canaandavis** [comment]
I think we should be generating a salt on the fly with Bcrypt.  Here is an [example](https://github.com/ncb000gt/node.bcrypt.js/#usage) on their docs.

Would also like to pull out the register logic into it's own module, you have any objects to that?

**Comment by mistakevin** [comment]
> I think we should be generating a salt on the fly with Bcrypt. Here is an example on their docs.
We need to keep the salt constant so that the passwords will work. I'm just postponing it until I get https://github.com/mistakevin/aca-campus/issues/3 (reset email) up

> Would also like to pull out the register logic into it's own module, you have any objects to that?
Def should be put into the users controller or it's own
